export let ammoPenData = [
  {
    "category": "12 Gauge Shot",
    "wikiCategory": "12x70mm",
    "ammoTypes": [
      {
        "category": "12 Gauge Shot",
        "wikiCategory": "12x70mm",
        "name": "5.25mm Buckshot",
        "damage": "34",
        "penValue": "1",
        "armorPenPerc": "15",
        "fragChance": "0%",
        "penArm1": "3",
        "penArm2": "3",
        "penArm3": "3",
        "penArm4": "3",
        "penArm5": "3",
        "penArm6": "3"
      },
      {
        "category": "12 Gauge Shot",
        "wikiCategory": "12x70mm",
        "name": "8.5mm Buckshot \"Magnum\"",
        "damage": "44",
        "penValue": "2",
        "armorPenPerc": "26",
        "fragChance": "0%",
        "penArm1": "3",
        "penArm2": "3",
        "penArm3": "3",
        "penArm4": "3",
        "penArm5": "3",
        "penArm6": "3"
      },
      {
        "category": "12 Gauge Shot",
        "wikiCategory": "12x70mm",
        "name": "6.5mm Buckshot \"Express\"",
        "damage": "29",
        "penValue": "3",
        "armorPenPerc": "26",
        "fragChance": "0%",
        "penArm1": "3",
        "penArm2": "3",
        "penArm3": "3",
        "penArm4": "3",
        "penArm5": "3",
        "penArm6": "3"
      },
      {
        "category": "12 Gauge Shot",
        "wikiCategory": "12x70mm",
        "name": "7mm Buckshot",
        "damage": "32",
        "penValue": "3",
        "armorPenPerc": "26",
        "fragChance": "0%",
        "penArm1": "3",
        "penArm2": "3",
        "penArm3": "3",
        "penArm4": "3",
        "penArm5": "3",
        "penArm6": "3"
      },
      {
        "category": "12 Gauge Shot",
        "wikiCategory": "12x70mm",
        "name": "Flechette",
        "damage": "19",
        "penValue": "28",
        "armorPenPerc": "26",
        "fragChance": "0%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "5",
        "penArm5": "5",
        "penArm6": "4"
      }
    ]
  },
  {
    "category": "12 Gauge Slugs",
    "wikiCategory": "12x70mm",
    "ammoTypes": [
      {
        "category": "12 Gauge Slugs",
        "wikiCategory": "12x70mm",
        "name": "RIP Slug",
        "damage": "235",
        "penValue": "0",
        "armorPenPerc": "11",
        "fragChance": "100%",
        "penArm1": "0",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "12 Gauge Slugs",
        "wikiCategory": "12x70mm",
        "name": "Superformance HP Slug",
        "damage": "190",
        "penValue": "2",
        "armorPenPerc": "12",
        "fragChance": "39%",
        "penArm1": "0",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "12 Gauge Slugs",
        "wikiCategory": "12x70mm",
        "name": "Grizzly 40 Slug",
        "damage": "170",
        "penValue": "12",
        "armorPenPerc": "48",
        "fragChance": "12%",
        "penArm1": "6",
        "penArm2": "2",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "12 Gauge Slugs",
        "wikiCategory": "12x70mm",
        "name": "HP Copper Sabot Premier",
        "damage": "160",
        "penValue": "13",
        "armorPenPerc": "46",
        "fragChance": "38%",
        "penArm1": "6",
        "penArm2": "2",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "12 Gauge Slugs",
        "wikiCategory": "12x70mm",
        "name": "Led Slug",
        "damage": "147",
        "penValue": "15",
        "armorPenPerc": "45",
        "fragChance": "20%",
        "penArm1": "6",
        "penArm2": "4",
        "penArm3": "1",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "12 Gauge Slugs",
        "wikiCategory": "12x70mm",
        "name": "Dual Sabot Slug",
        "damage": "75",
        "penValue": "17",
        "armorPenPerc": "65",
        "fragChance": "10%",
        "penArm1": "6",
        "penArm2": "5",
        "penArm3": "2",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "12 Gauge Slugs",
        "wikiCategory": "12x70mm",
        "name": "Slug \"Poleva-3\"",
        "damage": "130",
        "penValue": "17",
        "armorPenPerc": "40",
        "fragChance": "20%",
        "penArm1": "6",
        "penArm2": "5",
        "penArm3": "1",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "12 Gauge Slugs",
        "wikiCategory": "12x70mm",
        "name": "FTX Custom Lite Slug",
        "damage": "153",
        "penValue": "18",
        "armorPenPerc": "50",
        "fragChance": "10%",
        "penArm1": "6",
        "penArm2": "5",
        "penArm3": "1",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "12 Gauge Slugs",
        "wikiCategory": "12x70mm",
        "name": "Slug \"Poleva-6u\"",
        "damage": "140",
        "penValue": "20",
        "armorPenPerc": "50",
        "fragChance": "15%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "2",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "12 Gauge Slugs",
        "wikiCategory": "12x70mm",
        "name": "Shell With .50 BMG (Tracer)",
        "damage": "177",
        "penValue": "23",
        "armorPenPerc": "57",
        "fragChance": "5%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "3",
        "penArm4": "1",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "12 Gauge Slugs",
        "wikiCategory": "12x70mm",
        "name": "AP 20 Slug",
        "damage": "164",
        "penValue": "32",
        "armorPenPerc": "65",
        "fragChance": "3%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "3",
        "penArm5": "1",
        "penArm6": "0"
      }
    ]
  },
  {
    "category": "20 Gauge",
    "wikiCategory": "20x70mm",
    "ammoTypes": [
      {
        "category": "20 Gauge",
        "wikiCategory": "20x70mm",
        "name": "5.6mm Buckshot",
        "damage": "25",
        "penValue": "1",
        "armorPenPerc": "12",
        "fragChance": "0%",
        "penArm1": "3",
        "penArm2": "3",
        "penArm3": "3",
        "penArm4": "3",
        "penArm5": "3",
        "penArm6": "3"
      },
      {
        "category": "20 Gauge",
        "wikiCategory": "20x70mm",
        "name": "6.2mm Buckshot",
        "damage": "21",
        "penValue": "2",
        "armorPenPerc": "13",
        "fragChance": "0%",
        "penArm1": "3",
        "penArm2": "3",
        "penArm3": "3",
        "penArm4": "3",
        "penArm5": "3",
        "penArm6": "3"
      },
      {
        "category": "20 Gauge",
        "wikiCategory": "20x70mm",
        "name": "7.5mm Buckshot",
        "damage": "24",
        "penValue": "3",
        "armorPenPerc": "14",
        "fragChance": "0%",
        "penArm1": "3",
        "penArm2": "3",
        "penArm3": "3",
        "penArm4": "3",
        "penArm5": "3",
        "penArm6": "3"
      },
      {
        "category": "20 Gauge",
        "wikiCategory": "20x70mm",
        "name": "7.3mm Buckshot",
        "damage": "22",
        "penValue": "3",
        "armorPenPerc": "13",
        "fragChance": "0%",
        "penArm1": "3",
        "penArm2": "3",
        "penArm3": "3",
        "penArm4": "3",
        "penArm5": "3",
        "penArm6": "3"
      },
      {
        "category": "20 Gauge",
        "wikiCategory": "20x70mm",
        "name": "Devastator Slug",
        "damage": "188",
        "penValue": "4",
        "armorPenPerc": "13",
        "fragChance": "100%",
        "penArm1": "1",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "20 Gauge",
        "wikiCategory": "20x70mm",
        "name": "Slug \"Poleva-3\"",
        "damage": "110",
        "penValue": "14",
        "armorPenPerc": "35",
        "fragChance": "20%",
        "penArm1": "6",
        "penArm2": "2",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "20 Gauge",
        "wikiCategory": "20x70mm",
        "name": "Star Slug",
        "damage": "134",
        "penValue": "16",
        "armorPenPerc": "42",
        "fragChance": "10%",
        "penArm1": "6",
        "penArm2": "5",
        "penArm3": "1",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "20 Gauge",
        "wikiCategory": "20x70mm",
        "name": "Slug \"Poleva-6u\"",
        "damage": "120",
        "penValue": "17",
        "armorPenPerc": "40",
        "fragChance": "15%",
        "penArm1": "6",
        "penArm2": "5",
        "penArm3": "1",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      }
    ]
  },
  {
    "category": "9x18mm",
    "wikiCategory": "9x18mm Makarov",
    "ammoTypes": [
      {
        "category": "9x18mm",
        "wikiCategory": "9x18mm Makarov",
        "name": "SP8",
        "damage": "67",
        "penValue": "1",
        "armorPenPerc": "2",
        "fragChance": "60%",
        "penArm1": "0",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x18mm",
        "wikiCategory": "9x18mm Makarov",
        "name": "SP7",
        "damage": "77",
        "penValue": "2",
        "armorPenPerc": "5",
        "fragChance": "2%",
        "penArm1": "0",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x18mm",
        "wikiCategory": "9x18mm Makarov",
        "name": "PSV",
        "damage": "69",
        "penValue": "3",
        "armorPenPerc": "5",
        "fragChance": "40%",
        "penArm1": "0",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x18mm",
        "wikiCategory": "9x18mm Makarov",
        "name": "P gzh",
        "damage": "50",
        "penValue": "5",
        "armorPenPerc": "16",
        "fragChance": "25%",
        "penArm1": "2",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x18mm",
        "wikiCategory": "9x18mm Makarov",
        "name": "PSO gzh",
        "damage": "54",
        "penValue": "5",
        "armorPenPerc": "13",
        "fragChance": "35%",
        "penArm1": "2",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x18mm",
        "wikiCategory": "9x18mm Makarov",
        "name": "PS gs PPO",
        "damage": "55",
        "penValue": "6",
        "armorPenPerc": "16",
        "fragChance": "25%",
        "penArm1": "3",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x18mm",
        "wikiCategory": "9x18mm Makarov",
        "name": "PRS gs",
        "damage": "58",
        "penValue": "6",
        "armorPenPerc": "16",
        "fragChance": "30%",
        "penArm1": "3",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x18mm",
        "wikiCategory": "9x18mm Makarov",
        "name": "PPE gzh",
        "damage": "61",
        "penValue": "7",
        "armorPenPerc": "15",
        "fragChance": "35%",
        "penArm1": "4",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x18mm",
        "wikiCategory": "9x18mm Makarov",
        "name": "PPT gzh",
        "damage": "59",
        "penValue": "8",
        "armorPenPerc": "22",
        "fragChance": "17%",
        "penArm1": "5",
        "penArm2": "1",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x18mm",
        "wikiCategory": "9x18mm Makarov",
        "name": "PST gzh",
        "damage": "50",
        "penValue": "12",
        "armorPenPerc": "26",
        "fragChance": "20%",
        "penArm1": "6",
        "penArm2": "1",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x18mm",
        "wikiCategory": "9x18mm Makarov",
        "name": "RG028 gzh",
        "damage": "65",
        "penValue": "13",
        "armorPenPerc": "26",
        "fragChance": "2%",
        "penArm1": "6",
        "penArm2": "2",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x18mm",
        "wikiCategory": "9x18mm Makarov",
        "name": "BZT gzh",
        "damage": "55",
        "penValue": "16",
        "armorPenPerc": "28",
        "fragChance": "17%",
        "penArm1": "6",
        "penArm2": "4",
        "penArm3": "1",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x18mm",
        "wikiCategory": "9x18mm Makarov",
        "name": "PBM",
        "damage": "44",
        "penValue": "22",
        "armorPenPerc": "30",
        "fragChance": "16%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "2",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x18mm",
        "wikiCategory": "9x18mm Makarov",
        "name": "PMM",
        "damage": "56",
        "penValue": "25",
        "armorPenPerc": "33",
        "fragChance": "17%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "3",
        "penArm4": "1",
        "penArm5": "0",
        "penArm6": "0"
      }
    ]
  },
  {
    "category": "7.62x25mm",
    "wikiCategory": "7.62x25mm Tokarev",
    "ammoTypes": [
      {
        "category": "7.62x25mm",
        "wikiCategory": "7.62x25mm Tokarev",
        "name": "LRNPC",
        "damage": "66",
        "penValue": "5",
        "armorPenPerc": "27",
        "fragChance": "35%",
        "penArm1": "3",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "7.62x25mm",
        "wikiCategory": "7.62x25mm Tokarev",
        "name": "LRN",
        "damage": "64",
        "penValue": "6",
        "armorPenPerc": "28",
        "fragChance": "35%",
        "penArm1": "3",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "7.62x25mm",
        "wikiCategory": "7.62x25mm Tokarev",
        "name": "FMJ43",
        "damage": "60",
        "penValue": "8",
        "armorPenPerc": "29",
        "fragChance": "25%",
        "penArm1": "5",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "7.62x25mm",
        "wikiCategory": "7.62x25mm Tokarev",
        "name": "akbs",
        "damage": "58",
        "penValue": "9",
        "armorPenPerc": "32",
        "fragChance": "25%",
        "penArm1": "5",
        "penArm2": "1",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "7.62x25mm",
        "wikiCategory": "7.62x25mm Tokarev",
        "name": "P Gl",
        "damage": "58",
        "penValue": "10",
        "armorPenPerc": "32",
        "fragChance": "25%",
        "penArm1": "6",
        "penArm2": "1",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "7.62x25mm",
        "wikiCategory": "7.62x25mm Tokarev",
        "name": "T Gzh (Tracer)",
        "damage": "60",
        "penValue": "12",
        "armorPenPerc": "34",
        "fragChance": "17%",
        "penArm1": "6",
        "penArm2": "1",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "7.62x25mm",
        "wikiCategory": "7.62x25mm Tokarev",
        "name": "Pst gzh",
        "damage": "50",
        "penValue": "24",
        "armorPenPerc": "36",
        "fragChance": "20%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "3",
        "penArm4": "1",
        "penArm5": "0",
        "penArm6": "0"
      }
    ]
  },
  {
    "category": "9x19mm",
    "wikiCategory": "9x19mm Parabellum",
    "ammoTypes": [
      {
        "category": "9x19mm",
        "wikiCategory": "9x19mm Parabellum",
        "name": "RIP",
        "damage": "102",
        "penValue": "2",
        "armorPenPerc": "11",
        "fragChance": "100%",
        "penArm1": "0",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x19mm",
        "wikiCategory": "9x19mm Parabellum",
        "name": "PSO gzh",
        "damage": "56",
        "penValue": "10",
        "armorPenPerc": "32",
        "fragChance": "25%",
        "penArm1": "6",
        "penArm2": "1",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x19mm",
        "wikiCategory": "9x19mm Parabellum",
        "name": "Luger CCI",
        "damage": "70",
        "penValue": "10",
        "armorPenPerc": "38",
        "fragChance": "25%",
        "penArm1": "6",
        "penArm2": "2",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x19mm",
        "wikiCategory": "9x19mm Parabellum",
        "name": "Green Tracer",
        "damage": "58",
        "penValue": "14",
        "armorPenPerc": "33",
        "fragChance": "15%",
        "penArm1": "6",
        "penArm2": "3",
        "penArm3": "1",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x19mm",
        "wikiCategory": "9x19mm Parabellum",
        "name": "PST gzh",
        "damage": "54",
        "penValue": "18",
        "armorPenPerc": "33",
        "fragChance": "15%",
        "penArm1": "6",
        "penArm2": "5",
        "penArm3": "1",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x19mm",
        "wikiCategory": "9x19mm Parabellum",
        "name": "AP 6.3",
        "damage": "52",
        "penValue": "25",
        "armorPenPerc": "48",
        "fragChance": "5%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "4",
        "penArm4": "2",
        "penArm5": "0",
        "penArm6": "0"
      }
    ]
  },
  {
    "category": "0.45",
    "wikiCategory": ".45 ACP",
    "ammoTypes": [
      {
        "category": "0.45",
        "wikiCategory": ".45 ACP",
        "name": "RIP",
        "damage": "127",
        "penValue": "3",
        "armorPenPerc": "12",
        "fragChance": "100%",
        "penArm1": "1",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "0.45",
        "wikiCategory": ".45 ACP",
        "name": "ACP",
        "damage": "72",
        "penValue": "19",
        "armorPenPerc": "36",
        "fragChance": "1%",
        "penArm1": "6",
        "penArm2": "5",
        "penArm3": "1",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      }
    ]
  },
  {
    "category": "9x21mm",
    "wikiCategory": "9x21mm Gyurza",
    "ammoTypes": [
      {
        "category": "9x21mm",
        "wikiCategory": "9x21mm Gyurza",
        "name": "sp12",
        "damage": "75",
        "penValue": "14",
        "armorPenPerc": "63",
        "fragChance": "35%",
        "penArm1": "6",
        "penArm2": "2",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x21mm",
        "wikiCategory": "9x21mm Gyurza",
        "name": "sp11",
        "damage": "70",
        "penValue": "16",
        "armorPenPerc": "44",
        "fragChance": "30%",
        "penArm1": "6",
        "penArm2": "3",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "9x21mm",
        "wikiCategory": "9x21mm Gyurza",
        "name": "sp10",
        "damage": "49",
        "penValue": "32",
        "armorPenPerc": "46",
        "fragChance": "20%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "5",
        "penArm4": "3",
        "penArm5": "1",
        "penArm6": "1"
      },
      {
        "category": "9x21mm",
        "wikiCategory": "9x21mm Gyurza",
        "name": "sp13",
        "damage": "62",
        "penValue": "36",
        "armorPenPerc": "47",
        "fragChance": "20%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "4",
        "penArm5": "1",
        "penArm6": "1"
      }
    ]
  },
  {
    "category": "5.7x28 mm",
    "wikiCategory": "5.7x28mm FN",
    "ammoTypes": [
      {
        "category": "5.7x28 mm",
        "wikiCategory": "5.7x28mm FN",
        "name": "r37f",
        "damage": "98",
        "penValue": "8",
        "armorPenPerc": "7",
        "fragChance": "100%",
        "penArm1": "4",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "5.7x28 mm",
        "wikiCategory": "5.7x28mm FN",
        "name": "ss198lf",
        "damage": "74",
        "penValue": "10",
        "armorPenPerc": "15",
        "fragChance": "80%",
        "penArm1": "6",
        "penArm2": "1",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "5.7x28 mm",
        "wikiCategory": "5.7x28mm FN",
        "name": "r37x",
        "damage": "81",
        "penValue": "11",
        "armorPenPerc": "14",
        "fragChance": "70%",
        "penArm1": "6",
        "penArm2": "1",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "5.7x28 mm",
        "wikiCategory": "5.7x28mm FN",
        "name": "ss197sr",
        "damage": "62",
        "penValue": "20",
        "armorPenPerc": "22",
        "fragChance": "50%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "2",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "5.7x28 mm",
        "wikiCategory": "5.7x28mm FN",
        "name": "l191 (Tracer)",
        "damage": "58",
        "penValue": "33",
        "armorPenPerc": "41",
        "fragChance": "20%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "3",
        "penArm5": "1",
        "penArm6": "1"
      },
      {
        "category": "5.7x28 mm",
        "wikiCategory": "5.7x28mm FN",
        "name": "sb193",
        "damage": "54",
        "penValue": "35",
        "armorPenPerc": "37",
        "fragChance": "20%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "4",
        "penArm5": "2",
        "penArm6": "1"
      },
      {
        "category": "5.7x28 mm",
        "wikiCategory": "5.7x28mm FN",
        "name": "ss190",
        "damage": "49",
        "penValue": "37",
        "armorPenPerc": "43",
        "fragChance": "20%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "5",
        "penArm5": "3",
        "penArm6": "1"
      }
    ]
  },
  {
    "category": "4.6x30 mm",
    "wikiCategory": "4.6x30mm HK",
    "ammoTypes": [
      {
        "category": "4.6x30 mm",
        "wikiCategory": "4.6x30mm HK",
        "name": "Action SX",
        "damage": "65",
        "penValue": "13",
        "armorPenPerc": "39",
        "fragChance": "50%",
        "penArm1": "6",
        "penArm2": "2",
        "penArm3": "1",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "4.6x30 mm",
        "wikiCategory": "4.6x30mm HK",
        "name": "FMJ SX",
        "damage": "43",
        "penValue": "30",
        "armorPenPerc": "41",
        "fragChance": "20%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "3",
        "penArm5": "1",
        "penArm6": "1"
      },
      {
        "category": "4.6x30 mm",
        "wikiCategory": "4.6x30mm HK",
        "name": "Subsonic SX",
        "damage": "41",
        "penValue": "34",
        "armorPenPerc": "46",
        "fragChance": "20%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "4",
        "penArm5": "3",
        "penArm6": "1"
      },
      {
        "category": "4.6x30 mm",
        "wikiCategory": "4.6x30mm HK",
        "name": "AP SX",
        "damage": "35",
        "penValue": "47",
        "armorPenPerc": "46",
        "fragChance": "10%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "5",
        "penArm6": "4"
      }
    ]
  },
  {
    "category": "9x39mm",
    "wikiCategory": "9x39mm",
    "ammoTypes": [
      {
        "category": "9x39mm",
        "wikiCategory": "9x39mm",
        "name": "sp5",
        "damage": "68",
        "penValue": "35",
        "armorPenPerc": "52",
        "fragChance": "20%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "5",
        "penArm5": "3",
        "penArm6": "2"
      },
      {
        "category": "9x39mm",
        "wikiCategory": "9x39mm",
        "name": "sp6",
        "damage": "58",
        "penValue": "43",
        "armorPenPerc": "60",
        "fragChance": "10%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "5",
        "penArm6": "4"
      },
      {
        "category": "9x39mm",
        "wikiCategory": "9x39mm",
        "name": "SPP",
        "damage": "67",
        "penValue": "45",
        "armorPenPerc": "56",
        "fragChance": "20%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "5",
        "penArm6": "4"
      },
      {
        "category": "9x39mm",
        "wikiCategory": "9x39mm",
        "name": "BP",
        "damage": "60",
        "penValue": "50",
        "armorPenPerc": "68",
        "fragChance": "10%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "6",
        "penArm6": "5"
      }
    ]
  },
  {
    "category": "0.366",
    "wikiCategory": ".366 TKM",
    "ammoTypes": [
      {
        "category": "0.366",
        "wikiCategory": ".366 TKM",
        "name": "Geksa",
        "damage": "93",
        "penValue": "14",
        "armorPenPerc": "38",
        "fragChance": "45%",
        "penArm1": "6",
        "penArm2": "3",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "0.366",
        "wikiCategory": ".366 TKM",
        "name": "FMJ",
        "damage": "88",
        "penValue": "23",
        "armorPenPerc": "41",
        "fragChance": "25%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "3",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "0.366",
        "wikiCategory": ".366 TKM",
        "name": "EKO",
        "damage": "65",
        "penValue": "30",
        "armorPenPerc": "30",
        "fragChance": "20%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "5",
        "penArm4": "2",
        "penArm5": "0",
        "penArm6": "0"
      }
    ]
  },
  {
    "category": "5.45x39 mm",
    "wikiCategory": "5.45x39mm",
    "ammoTypes": [
      {
        "category": "5.45x39 mm",
        "wikiCategory": "5.45x39mm",
        "name": "SP",
        "damage": "68",
        "penValue": "11",
        "armorPenPerc": "34",
        "fragChance": "45%",
        "penArm1": "6",
        "penArm2": "1",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "5.45x39 mm",
        "wikiCategory": "5.45x39mm",
        "name": "HP",
        "damage": "74",
        "penValue": "11",
        "armorPenPerc": "20",
        "fragChance": "35%",
        "penArm1": "6",
        "penArm2": "1",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "5.45x39 mm",
        "wikiCategory": "5.45x39mm",
        "name": "PRS",
        "damage": "60",
        "penValue": "14",
        "armorPenPerc": "29",
        "fragChance": "30%",
        "penArm1": "6",
        "penArm2": "2",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "5.45x39 mm",
        "wikiCategory": "5.45x39mm",
        "name": "US",
        "damage": "65",
        "penValue": "15",
        "armorPenPerc": "34",
        "fragChance": "10%",
        "penArm1": "6",
        "penArm2": "3",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "5.45x39 mm",
        "wikiCategory": "5.45x39mm",
        "name": "FMJ",
        "damage": "54",
        "penValue": "20",
        "armorPenPerc": "30",
        "fragChance": "25%",
        "penArm1": "6",
        "penArm2": "5",
        "penArm3": "1",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "5.45x39 mm",
        "wikiCategory": "5.45x39mm",
        "name": "T (Tracer)",
        "damage": "57",
        "penValue": "20",
        "armorPenPerc": "38",
        "fragChance": "16%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "1",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "5.45x39 mm",
        "wikiCategory": "5.45x39mm",
        "name": "PS",
        "damage": "50",
        "penValue": "25",
        "armorPenPerc": "35",
        "fragChance": "40%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "4",
        "penArm4": "1",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "5.45x39 mm",
        "wikiCategory": "5.45x39mm",
        "name": "PP",
        "damage": "46",
        "penValue": "30",
        "armorPenPerc": "32",
        "fragChance": "17%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "3",
        "penArm5": "1",
        "penArm6": "0"
      },
      {
        "category": "5.45x39 mm",
        "wikiCategory": "5.45x39mm",
        "name": "BP",
        "damage": "48",
        "penValue": "32",
        "armorPenPerc": "41",
        "fragChance": "16%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "4",
        "penArm5": "2",
        "penArm6": "0"
      },
      {
        "category": "5.45x39 mm",
        "wikiCategory": "5.45x39mm",
        "name": "BT (Tracer)",
        "damage": "44",
        "penValue": "37",
        "armorPenPerc": "49",
        "fragChance": "16%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "5",
        "penArm5": "3",
        "penArm6": "1"
      },
      {
        "category": "5.45x39 mm",
        "wikiCategory": "5.45x39mm",
        "name": "BS",
        "damage": "40",
        "penValue": "51",
        "armorPenPerc": "57",
        "fragChance": "17%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "6",
        "penArm6": "5"
      },
      {
        "category": "5.45x39 mm",
        "wikiCategory": "5.45x39mm",
        "name": "7n39",
        "damage": "37",
        "penValue": "62",
        "armorPenPerc": "60",
        "fragChance": "2%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "6",
        "penArm6": "6"
      }
    ]
  },
  {
    "category": "5.56x45 mm",
    "wikiCategory": "5.56x45mm NATO",
    "ammoTypes": [
      {
        "category": "5.56x45 mm",
        "wikiCategory": "5.56x45mm NATO",
        "name": "Warmage",
        "damage": "85",
        "penValue": "3",
        "armorPenPerc": "14",
        "fragChance": "90%",
        "penArm1": "1",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "5.56x45 mm",
        "wikiCategory": "5.56x45mm NATO",
        "name": "55_HP",
        "damage": "75",
        "penValue": "9",
        "armorPenPerc": "22",
        "fragChance": "70%",
        "penArm1": "5",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "5.56x45 mm",
        "wikiCategory": "5.56x45mm NATO",
        "name": "MK_255_Mod_0",
        "damage": "60",
        "penValue": "17",
        "armorPenPerc": "32",
        "fragChance": "3%",
        "penArm1": "6",
        "penArm2": "4",
        "penArm3": "1",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "5.56x45 mm",
        "wikiCategory": "5.56x45mm NATO",
        "name": "M856 (Tracer)",
        "damage": "55",
        "penValue": "23",
        "armorPenPerc": "34",
        "fragChance": "33%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "3",
        "penArm4": "1",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "5.56x45 mm",
        "wikiCategory": "5.56x45mm NATO",
        "name": "FMJ",
        "damage": "52",
        "penValue": "24",
        "armorPenPerc": "33",
        "fragChance": "50%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "4",
        "penArm4": "1",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "5.56x45 mm",
        "wikiCategory": "5.56x45mm NATO",
        "name": "M855",
        "damage": "49",
        "penValue": "26",
        "armorPenPerc": "37",
        "fragChance": "40%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "4",
        "penArm4": "2",
        "penArm5": "1",
        "penArm6": "0"
      },
      {
        "category": "5.56x45 mm",
        "wikiCategory": "5.56x45mm NATO",
        "name": "M856A1 (Tracer)",
        "damage": "51",
        "penValue": "37",
        "armorPenPerc": "52",
        "fragChance": "33%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "5",
        "penArm5": "3",
        "penArm6": "1"
      },
      {
        "category": "5.56x45 mm",
        "wikiCategory": "5.56x45mm NATO",
        "name": "M855A1",
        "damage": "44",
        "penValue": "40",
        "armorPenPerc": "52",
        "fragChance": "34%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "4",
        "penArm6": "2"
      },
      {
        "category": "5.56x45 mm",
        "wikiCategory": "5.56x45mm NATO",
        "name": "M995",
        "damage": "41",
        "penValue": "53",
        "armorPenPerc": "58",
        "fragChance": "32%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "6",
        "penArm6": "5"
      }
    ]
  },
  {
    "category": "7.62x39 mm",
    "wikiCategory": "7.62x39mm",
    "ammoTypes": [
      {
        "category": "7.62x39 mm",
        "wikiCategory": "7.62x39mm",
        "name": "HP",
        "damage": "83",
        "penValue": "15",
        "armorPenPerc": "35",
        "fragChance": "26%",
        "penArm1": "6",
        "penArm2": "4",
        "penArm3": "1",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "7.62x39 mm",
        "wikiCategory": "7.62x39mm",
        "name": "US",
        "damage": "56",
        "penValue": "29",
        "armorPenPerc": "42",
        "fragChance": "8%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "5",
        "penArm4": "3",
        "penArm5": "1",
        "penArm6": "0"
      },
      {
        "category": "7.62x39 mm",
        "wikiCategory": "7.62x39mm",
        "name": "T45M (Tracer)",
        "damage": "62",
        "penValue": "31",
        "armorPenPerc": "46",
        "fragChance": "12%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "3",
        "penArm5": "2",
        "penArm6": "1"
      },
      {
        "category": "7.62x39 mm",
        "wikiCategory": "7.62x39mm",
        "name": "PS",
        "damage": "54",
        "penValue": "34",
        "armorPenPerc": "52",
        "fragChance": "25%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "4",
        "penArm5": "3",
        "penArm6": "1"
      },
      {
        "category": "7.62x39 mm",
        "wikiCategory": "7.62x39mm",
        "name": "BP",
        "damage": "58",
        "penValue": "47",
        "armorPenPerc": "63",
        "fragChance": "12%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "5",
        "penArm6": "4"
      }
    ]
  },
  {
    "category": "7.62x51 mm",
    "wikiCategory": "7.62x51mm NATO",
    "ammoTypes": [
      {
        "category": "7.62x51 mm",
        "wikiCategory": "7.62x51mm NATO",
        "name": "Ultra Nosler",
        "damage": "102",
        "penValue": "15",
        "armorPenPerc": "20",
        "fragChance": "70%",
        "penArm1": "6",
        "penArm2": "4",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "7.62x51 mm",
        "wikiCategory": "7.62x51mm NATO",
        "name": "BPZ FMJ",
        "damage": "88",
        "penValue": "31",
        "armorPenPerc": "33",
        "fragChance": "25%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "2",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "7.62x51 mm",
        "wikiCategory": "7.62x51mm NATO",
        "name": "TPZ SP",
        "damage": "60",
        "penValue": "36",
        "armorPenPerc": "40",
        "fragChance": "20%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "5",
        "penArm5": "2",
        "penArm6": "0"
      },
      {
        "category": "7.62x51 mm",
        "wikiCategory": "7.62x51mm NATO",
        "name": "M80",
        "damage": "80",
        "penValue": "41",
        "armorPenPerc": "66",
        "fragChance": "17%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "4",
        "penArm6": "3"
      },
      {
        "category": "7.62x51 mm",
        "wikiCategory": "7.62x51mm NATO",
        "name": "M62 (Tracer)",
        "damage": "79",
        "penValue": "54",
        "armorPenPerc": "75",
        "fragChance": "14%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "6",
        "penArm6": "5"
      },
      {
        "category": "7.62x51 mm",
        "wikiCategory": "7.62x51mm NATO",
        "name": "M61",
        "damage": "70",
        "penValue": "68",
        "armorPenPerc": "83",
        "fragChance": "13%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "6",
        "penArm6": "6"
      }
    ]
  },
  {
    "category": "7.62x54R",
    "wikiCategory": "7.62x54mmR",
    "ammoTypes": [
      {
        "category": "7.62x54R",
        "wikiCategory": "7.62x54mmR",
        "name": "T-46M (Tracer)",
        "damage": "82",
        "penValue": "41",
        "armorPenPerc": "83",
        "fragChance": "18%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "4",
        "penArm6": "3"
      },
      {
        "category": "7.62x54R",
        "wikiCategory": "7.62x54mmR",
        "name": "LPS_Gzh",
        "damage": "81",
        "penValue": "42",
        "armorPenPerc": "78",
        "fragChance": "18%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "4",
        "penArm6": "3"
      },
      {
        "category": "7.62x54R",
        "wikiCategory": "7.62x54mmR",
        "name": "7N1",
        "damage": "86",
        "penValue": "45",
        "armorPenPerc": "84",
        "fragChance": "8%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "5",
        "penArm6": "4"
      },
      {
        "category": "7.62x54R",
        "wikiCategory": "7.62x54mmR",
        "name": "7BT1 (Tracer)",
        "damage": "78",
        "penValue": "59",
        "armorPenPerc": "87",
        "fragChance": "8%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "6",
        "penArm6": "6"
      },
      {
        "category": "7.62x54R",
        "wikiCategory": "7.62x54mmR",
        "name": "SNB",
        "damage": "75",
        "penValue": "62",
        "armorPenPerc": "87",
        "fragChance": "8%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "6",
        "penArm6": "6"
      },
      {
        "category": "7.62x54R",
        "wikiCategory": "7.62x54mmR",
        "name": "7n37",
        "damage": "72",
        "penValue": "70",
        "armorPenPerc": "88",
        "fragChance": "8%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "6",
        "penArm6": "6"
      }
    ]
  },
  {
    "category": "12.7x55 mm",
    "wikiCategory": "12.7x55mm STs-130",
    "ammoTypes": [
      {
        "category": "12.7x55 mm",
        "wikiCategory": "12.7x55mm STs-130",
        "name": "ps12a",
        "damage": "165",
        "penValue": "10",
        "armorPenPerc": "22",
        "fragChance": "70%",
        "penArm1": "6",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "12.7x55 mm",
        "wikiCategory": "12.7x55mm STs-130",
        "name": "ps12",
        "damage": "115",
        "penValue": "28",
        "armorPenPerc": "60",
        "fragChance": "30%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "5",
        "penArm4": "2",
        "penArm5": "1",
        "penArm6": "0"
      },
      {
        "category": "12.7x55 mm",
        "wikiCategory": "12.7x55mm STs-130",
        "name": "ps12b",
        "damage": "102",
        "penValue": "46",
        "armorPenPerc": "57",
        "fragChance": "30%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "5",
        "penArm6": "4"
      }
    ]
  },
  {
    "category": "Mounted Weapons",
    "wikiCategory": "Mounted Weapons",
    "ammoTypes": [
      {
        "category": "Mounted Weapons",
        "wikiCategory": "Mounted Weapons",
        "name": "30mm Grenade",
        "damage": "199",
        "penValue": "1",
        "armorPenPerc": "95",
        "fragChance": "0%",
        "penArm1": "0",
        "penArm2": "0",
        "penArm3": "0",
        "penArm4": "0",
        "penArm5": "0",
        "penArm6": "0"
      },
      {
        "category": "Mounted Weapons",
        "wikiCategory": "Mounted Weapons",
        "name": "12.7x108mm",
        "damage": "182",
        "penValue": "88",
        "armorPenPerc": "88",
        "fragChance": "17%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "6",
        "penArm6": "6"
      },
      {
        "category": "Mounted Weapons",
        "wikiCategory": "Mounted Weapons",
        "name": "12.7x108mm Tracer",
        "damage": "199",
        "penValue": "80",
        "armorPenPerc": "95",
        "fragChance": "17%",
        "penArm1": "6",
        "penArm2": "6",
        "penArm3": "6",
        "penArm4": "6",
        "penArm5": "6",
        "penArm6": "6"
      },
      // {
      //   "category": "Mounted Weapons",
      //   "wikiCategory": "Mounted Weapons"
      // }
    ]
  }
];